## AI Labs
## G. Castro Oct. 2019
## docker-compose config file
## deploys production boost1

---
version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432 # access database from host at localhost:5432
    env_file: 
      - .env
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

 
