## AI Labs
## G. Castro Oct. 2019
## docker-compose config file
## deploys production boost1

---
version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432 # access database from host at localhost:5432
    env_file: 
      - .env
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  
  flask:
    image: ailabsuk/boost_backend
    environment: 
      - FLASK_APP=/flask/src/hello.py
      - FLASK_DEBUG=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - 5000:5000
    volumes:
      - .:/flask/src
    entrypoint: 
      - /flask/src/entrypoint.sh
    depends_on: 
      - postgres

 
